server:
  port: 9001
spring:
  application:
    name: hrm-sysmanage
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:com/xzp/hrm/mapper/*Mapper.xml
  type-aliases-package: com/xzp.hrm.domain,com/xzp.hrm.query